version: "3.7"
services:
  front-end:
    build: /front-end
    volumes: 
      - "./front-end:/app"
    ports:
      - 3000:3000
    
    container_name: "front-end" 
    
  
  backend:
    build: /back-end
    container_name: "back-end"
    volumes:
      - "./back-end:/app"
    ports:
      - 8000:8000

  db:
    image: redis:latest
    container_name: "redis"
  
